### ISSUE TITLE
Extract Dataset Error

### ISSUE THREAD

**Issue by schefs26** [pg-dev-git/tcrm_toolkit#2]
Error when extracting dataset: 
![image](https://user-images.githubusercontent.com/44069400/115961153-2a59ed00-a4e3-11eb-9782-dc02304a5ef7.png)
![image](https://user-images.githubusercontent.com/44069400/115961158-2e860a80-a4e3-11eb-9f4c-e01125121e75.png)

**Comment by pg-dev-git** [comment]
I was using a multiprocessing script that seems to not work when I build the exe. It spawns X amounts of child processes depending on the size of the dataset.

I previously had a multithreaded function that only uses 1 cpu core and decided to try multiprocessing because it's much faster.

The multithreaded function seems to work fine. I will revert to it on the next release today.

Thanks for testing this!
